// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	TransactionID pgtype.Int4
	LenderID      pgtype.Int4
	Borrower      pgtype.Int4
}

type Expense struct {
	TransactionID     int32
	TransactionName   pgtype.Text
	TransactionAmount pgtype.Int8
	UsersSpend        []byte
}

type User struct {
	UserID       int32
	Username     pgtype.Text
	EmailID      pgtype.Text
	MobileNumber pgtype.Numeric
}
