name: Migrate Prod DB
on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply PostgreSQL migrations
        uses: yakubique/postgresql-apply-migrations@v1.1
        with:
          migrations: './database/migrations'
          host: ${{ secrets.PG_HOST }}
          username: ${{ secrets.PG_USER }}
          password: ${{ secrets.PG_PWD }}
          db: ${{ secrets.PG_DB }}
