name: Migrate Prod DB
on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Apply PostgreSQL migrations
        uses: yakubique/postgresql-apply-migrations@v1.1
        with:
          migrations: './database/migrations'
          host: ${{ env.PG_HOST }}
          username: ${{ env.PG_USER }}
          password: ${{ env.PG_PWD }}
          db: ${{ env.PG_DB }}
